### PR TITLE
One typo corrected in manual v. 3.1.9

### PR DESCRIPTION
**Pull request by KZiemian**
In section 6.7 of manual v. 3.1.9 name "Problem Domains" was once written with small letter.

### CODE REVIEW

**Comment by muzimuzhi** [comment]
@KZiemian Is this PR ready to merge, or it is a draft and you will add more typo fixing commits?

**Comment by KZiemian** [comment]
This one is read to merge.

**Comment by hmenke** [comment]
Please first rebase to remove the unnecessary merge commit.

**Comment by hmenke** [comment]
Any progress here?

**Comment by hmenke** [comment]
Looks like it has been abandoned.

**Pull request closed without merging**
