### PR TITLE
doc: fix typo #986

### LINKED ISSUE #986: 58.6 Declaring Functions
Version: Manual for Version 3.1.8b

Page 709 
图片

### PR DESCRIPTION
**Pull request by muzimuzhi**
**Motivation for this change**

Fixes #986

**Checklist**

Please check the boxes to explicitly state your agreement to these terms:

- [x] Code changes are licensed under [GPLv2][GPL] + [LPPLv1.3c][LPPL]
- [x] Documentation changes are licensed under [FDLv1.2][FDL]

[GPL]: https://www.gnu.org/licenses/gpl-2.0.html
[LPPL]: https://www.latex-project.org/lppl/lppl-1-3c.txt
[FDL]: https://www.gnu.org/licenses/fdl-1.2.html

### CODE REVIEW

**Comment by hmenke** [comment]
For trivial things like this you really don't need to open a PR, unless you really want a second opinion.  Just push typo fixes directly to master.

**Comment by muzimuzhi** [comment]
I find myself don't have the push access to master. According to this [github doc](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization), only maintainer and admins can push to protected branched.

**Comment by hmenke** [comment]
Hm, but you're in the maintainers team.  Let me check the permissions.

**Comment by hmenke** [comment]
> Users with the Maintain role can push when required status checks pass.

That's annoying.  I want to require status checks to pass for pull requests, but that seems to apply to pushes as well.  To this end I have created a new unprotected staging branch.  Just push your changes there and when the checks have passed you should be able to push the same commits to master.  It's probably even a good idea anyway to develop on staging and then once in a while merge that into master.

**Comment by muzimuzhi** [comment]
Does this mean normal PRs are expected to merge to `staging` branch from now on? Is so, [PULL_REQUEST_TEMPLATE.md](https://github.com/pgf-tikz/pgf/blob/master/.github/PULL_REQUEST_TEMPLATE.md) will need an updation.

**Comment by muzimuzhi** [comment]
> Just push your changes there and when the checks have passed you should be able to push the same commits to master.

@hmenke When trying pushing checked commit https://github.com/pgf-tikz/pgf/commit/a02c45a62ccfdcf57a5e3a0fd0b2042aeee1a879 on `staging` to `master`, I still got the following "remote rejected" error.

```
$ git checkout master
$ git merge staging
$ git push origin master

Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:pgf-tikz/pgf.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:pgf-tikz/pgf.git'
```

According to the related GitHub Doc pages, it looks to me that the "status checks" rule only applies for PRs, not for direct pushing.

> When you enable branch restrictions, only users, teams, or apps that have been given permission can push to the protected branch. You can view and edit the users, teams, or apps with push access to a protected branch in the protected branch's settings.
> _from [Restrict who can push to matching branches](https://docs.github.com/en/enterprise-server@3.0/github/administering-a-repository/about-protected-branches#restrict-who-can-push-to-matching-branches)_

I'm ok to do development (if any) on `staging`, but as I asked in https://github.com/pgf-tikz/pgf/pull/987#issuecomment-765296082, then pgf might need to suggest `staging` as the preferred merge target.

**Comment by hmenke** [comment]
That's all too complicated.  I just deleted the branch protection rule for master, so you can push and merge without approving review and status checks passing.  The staging branch is gone now as well, because it's no longer needed..

**Pull request merged**
