### PR TITLE
typo?

### PR DESCRIPTION
**Pull request by thinbold**

### CODE REVIEW

**Review by Mo-Gul — APPROVED** [review]

**Review by hmenke — CHANGES_REQUESTED** [review]
sensible commit message?

**Comment by hmenke** [comment]
No activity. Requested changes are not being addressed.

**Comment by ilayn** [comment]
You can modify the commit message during merge so if the change is valid just push it in.

**Comment by hmenke** [comment]
No, I can't modify the commit message without rebasing.  I can write a custom message for the merge commit but that is not the same.

**Comment by ilayn** [comment]
You can always amend after the merge but yet another two lines and force-push, can be tiring at times.

**Comment by hmenke** [comment]
I went with this now:
```bash
curl -sSL https://github.com/pgf-tikz/pgf/pull/877.patch | sed 's/typo?/Fixed typo: of -> off/g' | git am -s
```
Still it would be much nicer if people just wrote sensible commit messages in the first place.

**Comment by thinbold** [comment]
Sorry about that. Will be careful next time. Have a nice day.

**Pull request closed without merging**
