### PR TITLE
docs: fix small typos

### PR DESCRIPTION
**Pull request by Freed-Wu**
**Motivation for this change**

**Checklist**

Please [signoff your commits][git-s] to explicitly state your agreement to the [Developer Certificate of Origin][DCO]. If that is not possible you may check the boxes below instead:

- [ ] Code changes are licensed under [GPLv2][GPL] + [LPPLv1.3c][LPPL]
- [x] Documentation changes are licensed under [FDLv1.2][FDL]

[git-s]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s
[DCO]: https://developercertificate.org
[GPL]: https://www.gnu.org/licenses/gpl-2.0.html
[LPPL]: https://www.latex-project.org/lppl/lppl-1-3c.txt
[FDL]: https://www.gnu.org/licenses/fdl-1.2.html

### CODE REVIEW

**Comment by Freed-Wu** [comment]
Does this pr has any problem?

**Comment by hmenke** [comment]
Nothing really, the changes are just very minor so I thought that you might want to add more. If that's really all you have for now, please rebase onto master and sign-off, then I'll merge it immediately.

**Comment by Freed-Wu** [comment]
OK, I have rebased :smile:

**Comment by muzimuzhi** [comment]
FYI, since Feb 2020, GitHub has an [**Update Branch** button](https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/) on its webpage.

**Pull request merged**
