### PR TITLE
Replace deprecated `arrows.spaced` and `arrows` used in codeexamples with `arrows.meta` (issue #698)

### PR DESCRIPTION
**Pull request by Mo-Gul**
I guess I did something wrong again when "updating" my branch because of a conflict. I guess the first two commits or at least the first commit shown below do not belong to this branch. Sorry ...

I will list the remaining instances of `arrows` arrows later in separate comments.

### CODE REVIEW

**Comment by Mo-Gul** [comment]
Remaining instance of arrow `serif cm` in

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/doc/generic/pgf/text-en/pgfmanual-en-main-body.tex#L463-L518

The nearest thing would be to replace the

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/doc/generic/pgf/text-en/pgfmanual-en-main-body.tex#L504

with

      } edge from parent [shorten >=-1pt,{Bar[width=7pt,line width=0.6pt]}-,line cap=butt]

which yields grafik (left with `serif cm`, right with `Bar`). A noticeable difference you will first see around a magnification of about 1000%. Here a [PDF](https://github.com/pgf-tikz/pgf/files/3613984/serif.cm.pdf) to check yourself.

**Comment by Mo-Gul** [comment]
Remaining instance of `latex'` in line 703 of

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/doc/generic/pgf/text-en/pgfmanual-en-tikz-matrices.tex#L694-L735

Here I don't have a clue how this could be replicated with the `arrows.meta` library. I suggest to replace it with either `Latex` or `Stealth`.

grafik

**Comment by Mo-Gul** [comment]
The library `circuits.ee.IEC` loads the `arrows` library

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/tex/generic/pgf/frontendlayer/tikz/libraries/circuits/tikzlibrarycircuits.ee.IEC.code.tex#L10

for the arrow tip `direction ee` 

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/tex/generic/pgf/libraries/shapes/circuits/pgflibraryshapes.gates.ee.code.tex#L144-L164

and is used in

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/doc/generic/pgf/text-en/pgfmanual-en-library-circuits.tex#L1894

https://github.com/pgf-tikz/pgf/blob/ee17ca51395308d7df7d8fe6f805c20ec69f8017/doc/generic/pgf/text-en/pgfmanual-en-library-circuits.tex#L1952-L1974

The nearest/best I could find here is the green arrow in
```latex
\documentclass[border=5pt]{standalone}
\usepackage{tikz}
    \usetikzlibrary{
        circuits.ee.IEC,
        arrows.meta,
    }
\begin{document}
    \begin{tikzpicture}
        \draw [ultra thick,-direction ee]       (0,0.4) -- +(0.5,0);
        \draw [
            opacity=0.5,
            ultra thick,red,
            -{Triangle[angle'=45,round]},
        ] (0,0.4) -- +(0.5,0);

        \draw [-direction ee]       (0,0.2) -- +(0.5,0);
        \draw [
            opacity=0.5,
            red,
            -{Triangle[angle=45:5pt,round]},
        ] (0,0.2) -- +(0.5,0);


        \draw [-direction ee]       (0,0.0) -- +(0.5,0);
        \draw [
            opacity=0.5,
            green,
            -{Triangle[angle=45:4.2pt 1.5,round]},
        ] (0,0.0) -- +(0.5,0);

        \draw [ultra thick,-direction ee]       (0,-0.2) -- +(0.5,0);
        \draw [
            opacity=0.5,
            ultra thick,green,
            -{Triangle[angle=45:4.2pt 1.5,round]},
        ] (0,-0.2) -- +(0.5,0);
    \end{tikzpicture}
\end{document}
```
which yields
grafik

**Comment by Mo-Gul** [comment]
Also currently it is not mentioned (any more) that there are some arrow tips loaded by default. See the old text

https://github.com/pgf-tikz/pgf/blob/709020fbdc7c227706f082bc382e9159cd939275/doc/generic/pgf/text-en/pgfmanual-en-library-arrows.tex#L27-L29

which was replaced in commit aa5d94b532b69a7d3e7a09e6b014b5dad38d35dc when the `arrows.meta` library was introduced. But they are still loaded by default as can be verified with the following MWE where I also show the corresponding `arrows.meta` arrow tips.

```latex
\documentclass[border=5pt]{standalone}
\usepackage{tikz}
    \usetikzlibrary{arrows.meta}
\begin{document}
\begin{tikzpicture}
    % default arrow tips
    \draw [red]      (0.4,0.9) -- (0.4,-0.1);
    \draw [-to]      (0,0.8) -- +(0.4,0);
    \draw [-stealth] (0,0.6) -- +(0.4,0);
    \draw [-latex]   (0,0.4) -- +(0.4,0);
    \draw [-space]   (0,0.2) -- +(0.4,0);
    \draw [-|]       (0,0.0) -- +(0.4,0);

    % corresponding `arrows.meta` tips
    \draw [red]      (0.6,0.9) -- (0.6,-0.1);
    \draw [-To]      (1,0.8) -- +(-0.4,0);
    \draw [-Stealth] (1,0.6) -- +(-0.4,0);
    \draw [-Latex]   (1,0.4) -- +(-0.4,0);
    \draw [-_]       (1,0.2) -- +(-0.4,0);
    \draw [-Bar]     (1,0.0) -- +(-0.4,0);
\end{tikzpicture}
\end{document}
```
yields
grafik

As can be seen, the sizes of the first three arrows are a bit larger in the `arrows.meta` library.

Shall somewhere stated (again) that there are these default arrow tips? And if yes, should they be redefined to the sizes of the `arrows.meta` tips? I personally would prefer that but of course for backward compatibility reasons that would be an issue.

**Comment by Mo-Gul** [comment]
@hmenke, do you just don't find some time to check this pull request or do I miss something that is still missing?

**Comment by hmenke** [comment]
I'm not sure whether we should really purge all uses of the old arrows from the manual.  After all, they are still there, they are still supported, and they will not go away in the future.

**Comment by Mo-Gul** [comment]
As long as there is not *one* sentence about the "old" arrows from the `arrows` library in the manual I would replace them. So people who are new to TikZ could be confused where these arrows are coming from. And since currently these arrows are written to be "deprecated" (several times) it absolutely makes sense to also not use them in the manual.

Of course that doesn't hinder people to still use the `arrows` library in future for those who already know it and have used it.

**Comment by hmenke** [comment]
Okay, I will rebase and merge soon.

**Review by hmenke — APPROVED** [review]

**Comment by hmenke** [comment]
Rebased and merged in https://github.com/pgf-tikz/pgf/compare/92faccff...09e9d2ef

**Pull request closed without merging**
